"use client";

import React, { useEffect, useState, useTransition } from "react";
import {
  Bot,
  CheckCircle2,
  XCircle,
  Loader2,
  Sparkles,
  Inbox,
} from "lucide-react";
import {
  fetchSecretaryTasks,
  markTaskDismissed,
  markTaskDone,
} from "@/services/secretary.service";
import { Button } from "@/components/ui/button";

// We import the type directly from our generated types
import type { Tables } from "@/types/supabase";
type SecretaryTask = Tables<"secretary_tasks">;

export function AiSecretaryTab() {
  const [tasks, setTasks] = useState<SecretaryTask[]>([]);
  const [loading, setLoading] = useState(true);
  const [isPending, startTransition] = useTransition();

  useEffect(() => {
    async function loadTasks() {
      try {
        const data = await fetchSecretaryTasks();
        setTasks(data);
      } catch (err) {
        console.error("Failed to load tasks:", err);
      } finally {
        setLoading(false);
      }
    }
    loadTasks();
  }, []);

  const handleAction = (taskId: string, action: "done" | "dismiss") => {
    // Optimistic update
    setTasks((prev) => prev.filter((t) => t.id !== taskId));

    startTransition(async () => {
      try {
        if (action === "done") {
          await markTaskDone(taskId);
        } else {
          await markTaskDismissed(taskId);
        }
      } catch (err) {
        console.error(`Failed to mark task as ${action}:`, err);
        // Rollback on failure (simplified)
        const data = await fetchSecretaryTasks();
        setTasks(data);
      }
    });
  };

  if (loading) {
    return (
      <div className="flex h-[50vh] flex-col items-center justify-center space-y-4 text-muted-foreground">
        <Loader2 className="h-8 w-8 animate-spin text-primary/50" />
        <p className="text-sm font-medium">Syncing with AI Secretary...</p>
      </div>
    );
  }

  if (tasks.length === 0) {
    return (
      <div className="flex h-[60vh] flex-col items-center justify-center space-y-6">
        <div className="flex h-20 w-20 items-center justify-center rounded-full bg-primary/10">
          <Sparkles className="h-10 w-10 text-primary" strokeWidth={1.5} />
        </div>
        <div className="space-y-2 text-center">
          <h2 className="text-2xl font-semibold tracking-tight text-foreground">
            You're all caught up!
          </h2>
          <p className="text-muted-foreground max-w-sm">
            Your AI Secretary is actively monitoring your workspace. Any new
            tasks will appear here.
          </p>
        </div>
      </div>
    );
  }

  return (
    <div className="mx-auto max-w-3xl space-y-8 pb-12">
      <div className="border-b border-border pb-6">
        <h1 className="text-2xl font-semibold tracking-tight text-foreground flex items-center gap-2">
          <Bot className="h-7 w-7 text-primary" />
          AI Secretary
        </h1>
        <p className="text-sm text-muted-foreground mt-2">
          Review and resolve automated tasks generated by your workspace AI.
        </p>
      </div>

      <div className="space-y-6">
        {tasks.map((task) => (
          <div
            key={task.id}
            className="group flex gap-5 animate-in fade-in slide-in-from-bottom-2 duration-500"
          >
            {/* Avatar */}
            <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-primary/10 ring-1 ring-primary/20">
              <Bot className="h-5 w-5 text-primary" />
            </div>

            {/* Message Body */}
            <div className="flex-1 space-y-3">
              <div className="rounded-2xl rounded-tl-sm bg-muted/50 p-5 border border-border/50">
                <div className="flex items-center justify-between gap-4 mb-2">
                  <h3 className="font-semibold text-foreground text-sm">
                    {task.title}
                  </h3>
                  <span className="text-[10px] uppercase tracking-wider font-semibold text-muted-foreground bg-background px-2 py-1 rounded-md border border-border">
                    {task.priority || "Standard"}
                  </span>
                </div>
                <p className="text-sm text-muted-foreground leading-relaxed">
                  {task.description}
                </p>
              </div>

              {/* Action Buttons */}
              <div className="flex items-center gap-3 pl-1">
                <Button
                  variant="default"
                  className="h-8 gap-2 rounded-full px-4 text-xs shadow-sm transition-transform hover:scale-105"
                  onClick={() => handleAction(task.id, "done")}
                  disabled={isPending}
                >
                  <CheckCircle2 className="h-3.5 w-3.5" />
                  Mark as Resolved
                </Button>
                <Button
                  variant="outline"
                  className="h-8 gap-2 rounded-full px-4 text-xs text-muted-foreground transition-transform hover:scale-105"
                  onClick={() => handleAction(task.id, "dismiss")}
                  disabled={isPending}
                >
                  <XCircle className="h-3.5 w-3.5" />
                  Dismiss
                </Button>
              </div>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
